name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Debug Step
      run: |
        ls -l         # Verifica permissões de arquivos
        env           # Exibe variáveis de ambiente
        java -version # Verifica versão do Java


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Deploy to Railway
      env:
        RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
      run: |
        curl -X POST "https://backboard.railway.app/deploy/webhook/196b72f8-4352-4b8d-9242-381cc502e064" \
        -H "Authorization: Bearer $RAILWAY_API_TOKEN" \
        -H "Content-Type: application/json"

